[package]
name = "usermgmt"
version = "0.4.8"
edition = "2021"
license-file = "LICENSE"
description = "Simultaneous Slurm and LDAP user management"
readme = "README.md"
rust-version = "1.64.0"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
confy = "0.4.0"
tempfile = "3.3.0"
rpassword = "6.0"
log = "0.4.16"
env_logger = "0.9.0"
ldap3 = "0.11.1"
maplit = "1.0.2"
ssh2 = "0.9.4"
once_cell = "1.17.1"
anyhow = { version = "1.0.70", features = ["backtrace"] }

[package.metadata.deb]
maintainer = "Dominik Wagner <dominik.wagner@th-nuernberg.de>"
copyright = "2023, Dominik Wagner <dominik.wagner@th-nuernberg.de>"
license-file = ["LICENSE", "4"]
extended-description = """\
A simple commandline tool for \
managing Slurm and LDAP users simultaneously."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    [
        "target/release/usermgmt",
        "usr/bin/",
        "755",
    ],
    [
        "README.md",
        "usr/share/doc/usermgmt/README",
        "644",
    ],
]
