[package]
name = "usermgmt"
version = "0.3.7"
edition = "2021"
license-file = "LICENSE"
description = "Simultaneous Slurm and LDAP user management"
readme = "README.md"

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
confy = "0.4.0"
tempfile = "3.3.0"
rpassword = "6.0"
log = "0.4.16"
env_logger = "0.9.0"
ldap3 = "0.10.5"
maplit = "1.0.2"
ssh2 = "0.3.1"

[package.metadata.deb]
maintainer = "Dominik Wagner <dominik.wagner@th-nuernberg.de>"
copyright = "2022, Dominik Wagner <dominik.wagner@th-nuernberg.de>"
license-file = ["LICENSE", "4"]
extended-description = """\
A simple commandline tool for \
managing Slurm and LDAP users simultaneously."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/usermgmt", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/usermgmt/README", "644"],
]
