# this configuration is set up for development 
# via docker container serving as end points for ldap and slurm nodes

student_default_qos = 'basic'
staff_default_qos = 'advanced'
student_qos = [
    'interactive',
    'basic',
]
staff_qos = [
    'interactive',
    'advanced',
]
valid_qos = [
    'interactive',
    'basic',
    'advanced',
]
valid_slurm_groups = [
    'staff',
    'student',
]
objectclass_common = [
    'inetOrgPerson',
    'ldapPublicKey',
    'organizationalPerson',
    'person',
    'posixAccount',
    'shadowAccount',
    'slurmRole',
    'top',       
]
compute_nodes = [
    'm0.host.de',
    'ml1.host.de',
]
# Static ip address of docker container as head node for development
head_node = '172.25.0.13'
default_ssh_user = 'dev_user'
home_host = '172.25.0.13'
nfs_host = 'nfs.server.de'
nfs_root_dir = '/mnt/md0/scratch'
compute_node_root_dir = '/mnt/md0/user'
filesystem = '/mnt/md0'
home_filesystem = '/dev/sdb4'
nfs_filesystem = '/dev/sda1'
quota_softlimit = '200G'
quota_hardlimit = '220G'
quota_nfs_softlimit = '200G'
quota_nfs_hardlimit = '220G'
quota_home_softlimit = '20G'
quota_home_hardlimit = '22G'
login_shell = '/bin/bash'
student_gid = 1002
staff_gid = 1001
faculty_gid = 1000
# In development the access to slurm is remote via a docker container
sacctmgr_path = 'sacctmgr'
ldap_domain_components = 'dc=example,dc=org'
ldap_org_unit = 'people'
ldap_server = 'ldap://localhost:389'
ldap_readonly_user = 'admin'
ldap_readonly_pw = 'admin'
include_dir_mgmt = false
use_homedir_helper = false 
run_slurm_remote = true
