student_default_qos = 'basic'
staff_default_qos = 'advanced'
student_qos = [
    'interactive',
    'basic',
    'gpubasic',
]
staff_qos = [
    'interactive',
    'advanced',
    'gpubasic',
]
valid_qos = [
    'interactive',
    'basic',
    'advanced',
    'ultimate',
    'bigmem',
    'gpubasic',
    'gpuultimate',
]
valid_slurm_groups = [
    'staff',
    'student',
]
objectclass_common = [
    'inetOrgPerson',
    'ldapPublicKey',
    'organizationalPerson',
    'person',
    'posixAccount',
    'shadowAccount',
    'slurmRole',
    'top',       
]
compute_nodes = [
    'ml0.informatik.fh-nuernberg.de',
    'ml1.informatik.fh-nuernberg.de',
    'ml2.informatik.fh-nuernberg.de',
]
login_shell = '/bin/bash'
student_gid = 1002
staff_gid = 1001
faculty_gid = 1000
sacctmgr_path = '/usr/local/bin/sacctmgr'
ldap_domain_components = 'dc=informatik,dc=fh-nuernberg,dc=de'
ldap_org_unit = 'people'
ldap_server = 'ldap://localhost:389'
ldif_template_path = './ldif'
