services:
  ldap:
    image: osixia/openldap:1.5.0 
    command: "--copy-service"
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - "./bootstrap_lidfs:/container/service/slapd/assets/config/bootstrap/ldif/custom"
      - ldap_database:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
        
volumes:
  ldap_database:
  ldap_config: 
  
