name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository content"
        uses: actions/checkout@v3
        
      - name: "Install needed rust toolchain stable"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
            
      - name: "Building project to see if it compiles and does not produce any warnings" 
        run: cargo clippy -- -Dwarnings
        
      - name: "Checking if all unit tests pass" 
        run: cargo test --verbose
