name: Release
# https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases#example-workflow-basic-usage
permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            build_tool: cross
          - target: aarch64-apple-darwin
            os: macos-latest
            build_tool: cross
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            build_tool: cargo
          - target: x86_64-apple-darwin
            os: macos-latest
            build_tool: cargo
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: usermgmt
          build_tool: ${{ matrix.build_tool }}
          target: ${{ matrix.target }}
          include: LICENSE,README.md
          tar: unix
          token: ${{ secrets.GITHUB_TOKEN }}
